/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import Storage.KategoriPemasukkanStorage;
import model.Hutang;
import Storage.HutangStorage;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author DICKY SAPUTRA
 */
public class HutangGUI extends javax.swing.JFrame {
int row;
HutangStorage hutangStorage = new HutangStorage();




    /**
     * Creates new form PengeluaranGUI
     */
    public HutangGUI()  {
        initComponents();
        getAllHutang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        caribtn = new javax.swing.JButton();
        cariField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        refreshbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        bayarbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablehutang = new javax.swing.JTable();
        btnTambahPengeluaran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HUTANG");

        editbtn.setBackground(new java.awt.Color(0, 153, 255));
        editbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\DICKY SAPUTRA\\Documents\\NetBeansProjects\\AplikasiKeuangan\\src\\main\\Java\\gambar\\ubah.png")); // NOI18N
        editbtn.setBorder(null);
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        hapusbtn.setBackground(new java.awt.Color(0, 153, 255));
        hapusbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\DICKY SAPUTRA\\Documents\\NetBeansProjects\\AplikasiKeuangan\\src\\main\\Java\\gambar\\delete.png")); // NOI18N
        hapusbtn.setBorder(null);
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        caribtn.setBackground(new java.awt.Color(0, 153, 255));
        caribtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\DICKY SAPUTRA\\Documents\\NetBeansProjects\\AplikasiKeuangan\\src\\main\\Java\\gambar\\cari.png")); // NOI18N
        caribtn.setBorder(null);
        caribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari");

        refreshbtn.setBackground(new java.awt.Color(0, 153, 255));
        refreshbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\DICKY SAPUTRA\\Documents\\NetBeansProjects\\AplikasiKeuangan\\src\\main\\Java\\gambar\\refresh.png")); // NOI18N
        refreshbtn.setBorder(null);
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        bayarbtn.setText("Bayar");
        bayarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarbtnActionPerformed(evt);
            }
        });

        jButton2.setText("Histori");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caribtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bayarbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editbtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshbtn)
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshbtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backbtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hapusbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caribtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bayarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        tablehutang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Judul Hutang", "Jumlah Hutang", "Status"
            }
        ));
        jScrollPane1.setViewportView(tablehutang);

        btnTambahPengeluaran.setBackground(new java.awt.Color(0, 153, 255));
        btnTambahPengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambahPengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengeluaran.setText("+Tambah");
        btnTambahPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTambahPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPengeluaranActionPerformed
        // TODO add your handling code here:
        TambahHutangGUIFORM tambah = new TambahHutangGUIFORM();
        tambah.setVisible(true);
        tambah.addWindowListener(new WindowAdapter(){public void windowClosed(WindowEvent e){getAllHutang();}});
    }//GEN-LAST:event_btnTambahPengeluaranActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        try {
        int selectedRow = tablehutang.getSelectedRow();
        int id_hutang = Integer.parseInt(tablehutang.getValueAt(selectedRow, 0).toString());
        String judul_hutang = tablehutang.getValueAt(selectedRow, 1).toString();
        String jumlahhutangString = tablehutang.getValueAt(selectedRow, 2).toString();
        String jumlahHutangCleaned = jumlahhutangString.replaceAll("[^\\d]", ""); 
        int jumlahHutangAwal = Integer.parseInt(jumlahHutangCleaned);
        int jumlah_hutang = jumlahHutangAwal/100;
        EditHutangGUIFORM edit = new EditHutangGUIFORM(id_hutang, judul_hutang, jumlah_hutang);
        edit.setVisible(true);
        edit.addWindowListener(new WindowAdapter() {
        public void windowClosed(WindowEvent e) {
            getAllHutang();
        }
    });
    } catch(Exception e) {
        e.printStackTrace();
}
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablehutang.getSelectedRow();
        int id_hutang = (int) tablehutang.getValueAt(selectedRow, 0);
        try {
        Hutang hutang = new Hutang(id_hutang);
        int rowsAffected = hutangStorage.deletePengeluaran(hutang);
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Hutang berhasil dihapus");
         } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus hutang");
        }
        }catch (SQLException e) {
            e.printStackTrace();
        }
        getAllHutang();
    }//GEN-LAST:event_hapusbtnActionPerformed
    
    private void caribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribtnActionPerformed
        // TODO add your handling code here:
        String keyword = cariField.getText();
        DefaultTableModel model = (DefaultTableModel) tablehutang.getModel();
        model.setRowCount(0);
        try {
            List<Hutang> listNgutang = hutangStorage.getDataHutangByJudul(keyword);
            if(!listNgutang.isEmpty()){
                for(Hutang hutang : listNgutang){
                Object [] row = {
                hutang.getId_hutang(),
                hutang.getJudul_hutang(),
                hutang.getJumlah_hutang(),
                hutang.getStatus()
                };
                model.addRow(row);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_caribtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        getAllHutang();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        new MainPageGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void bayarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablehutang.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih terlebih dahulu hutang yang ingin dibayar.");
        } else {
            int id_hutang = Integer.parseInt(tablehutang.getValueAt(selectedRow, 0).toString());
            BayarHutangFormGUI bayar = new BayarHutangFormGUI(id_hutang);
            bayar.setVisible(true);
            bayar.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                getAllHutang();
        }
        });
}

    }//GEN-LAST:event_bayarbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HistoriPembayaranHutangGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void getAllHutang() {
        try {
            NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            List<Hutang> listNgutang = hutangStorage.getDataHutang();
        
            DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID","Judul Hutang", "Jumlah Hutang", "Status"}
            );
        
            for (Hutang hutang : listNgutang ) {
                int id_hutang = hutang.getId_hutang();
                String judul_hutang = hutang.getJudul_hutang();
                int jumlah_hutang = hutang.getJumlah_hutang();
                String format_jumlah_hutang = formatter.format(jumlah_hutang);
                String status = hutang.getStatus();
            
                model.addRow(new Object[]{id_hutang, judul_hutang, format_jumlah_hutang, status});
            }
        
            tablehutang.setModel(model);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HutangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HutangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HutangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HutangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HutangGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton bayarbtn;
    private javax.swing.JButton btnTambahPengeluaran;
    private javax.swing.JTextField cariField;
    private javax.swing.JButton caribtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTable tablehutang;
    // End of variables declaration//GEN-END:variables
}
